Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
   Exclude:
    - "db/migrate/*.rb"

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 15
  CountComments: false
  Exclude:
    - "db/migrate/*.rb"
    - "features/step_definitions/*.rb"

Layout/LineLength:
  Max: 150
  Exclude:
    - "**/*_spec.rb"

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
      - "**/*_spec.rb"
      - "lib/tasks/**"
      - "spec/factories/*"
      - "spec/swagger_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/rails_helper.rb'
    - 'spec/response_helper.rb'
    - 'spec/controllers/concerns/respondable_spec.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'config/**/*'
    - 'ng/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'lib/tasks/**/*'
